<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>StarFoxZeroLocalizationTool</RootNamespace>
    <AssemblyName>StarFox Zero Localization Tool</AssemblyName>
    <Product>StarFox Zero Localization Tool</Product>
    <AssemblyTitle>StarFox Zero Localization Tool</AssemblyTitle>
    <Description>StarFox Zero Localization Tool</Description>
    <Company>Junior GBJ</Company>
    <ApplicationIcon>Fox.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Fox.ico" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
